**imports**

In [42]:
import torch
import torchvision
import torch.nn
import matplotlib.pyplot as plt
import numpy as np

**const for below demo** 

In [43]:
W = [[1, 1, 1],
    [1.5, 1.5, 1.5],
    [2, 2, 2]]

# 3x1
x = [[6], [7], [8]]

# 3x1
b = [[1], [1], [1]]

# Variable to store output
# 3x1
y = [[0], [0], [0]]

**numpy way**

makes arrays using the const shown above

In [44]:
W_np = np.array(W)

x_np = np.array(x)

faster way to make array

make an 3x1 array of only ones

In [45]:
b_np = np.ones((3, 1))

computes output using numpy

In [46]:
output = np.matmul(W_np, x_np) + b_np

lets print the result

In [47]:
print("Output:\n", output)
print("Output shape:\n", output.shape)


Output:
 [[22. ]
 [32.5]
 [43. ]]
Output shape:
 (3, 1)


**Now PyTorch**

In [48]:
W_torch = torch.FloatTensor(W)
x_torch = torch.FloatTensor(x)

b_torch = torch.ones(3, 1) #<-- i like this more no nested list

output = torch.matmul(W_torch, x_torch) + b_torch

lets print the results

In [49]:
print("Output:\n", output)
print("Output shape:\n", output.shape)

Output:
 tensor([[22.0000],
        [32.5000],
        [43.0000]])
Output shape:
 torch.Size([3, 1])


PyTorch was made with a lot of simallar functions as numpy to ease the transfer to it 

many of the functions from each import are able to be used with each other as shown below

In [50]:
np_array = np.random.random((3,4))

now im gonna convert to a PyTorch tensor

In [51]:
torch_tensor = torch.FloatTensor(np_array)

now back to a np array

In [52]:
np_array2 = torch_tensor.numpy()

lets print the results

In [53]:
print("Numpy array: \n", np_array2)
print("Tensor: \n", torch_tensor)

Numpy array: 
 [[0.00758165 0.45707014 0.5714444  0.3101216 ]
 [0.6052448  0.8700822  0.17943552 0.7085888 ]
 [0.7872151  0.44141665 0.21038875 0.36815923]]
Tensor: 
 tensor([[0.0076, 0.4571, 0.5714, 0.3101],
        [0.6052, 0.8701, 0.1794, 0.7086],
        [0.7872, 0.4414, 0.2104, 0.3682]])


**just pytorch now**

2d tensor with random

In [54]:
x = torch.rand(4, 5)

print('1D tensor \n', x)

1D tensor 
 tensor([[0.1804, 0.7949, 0.1835, 0.6104, 0.4437],
        [0.5266, 0.8692, 0.3603, 0.5641, 0.3395],
        [0.7823, 0.9499, 0.6799, 0.1660, 0.8330],
        [0.4939, 0.4465, 0.1734, 0.0952, 0.6535]])


scalar arithmetic on tensors

In [55]:
print('scalar multiplication\n', x * 10)
print('addtion and square\n', (x + 2)**2)
print('division\n', x / 10)

scalar multiplication
 tensor([[1.8044, 7.9490, 1.8349, 6.1037, 4.4370],
        [5.2659, 8.6920, 3.6030, 5.6406, 3.3950],
        [7.8228, 9.4986, 6.7989, 1.6596, 8.3302],
        [4.9394, 4.4650, 1.7340, 0.9523, 6.5354]])
addtion and square
 tensor([[4.7543, 7.8115, 4.7676, 6.8140, 5.9717],
        [6.3837, 8.2323, 5.5710, 6.5744, 5.4733],
        [7.7411, 8.7017, 7.1818, 4.6914, 8.0260],
        [6.2197, 5.9854, 4.7237, 4.3900, 7.0413]])
division
 tensor([[0.0180, 0.0795, 0.0183, 0.0610, 0.0444],
        [0.0527, 0.0869, 0.0360, 0.0564, 0.0340],
        [0.0782, 0.0950, 0.0680, 0.0166, 0.0833],
        [0.0494, 0.0447, 0.0173, 0.0095, 0.0654]])


mixing normal python functions

In [56]:
print('power and squar root\n', torch.sqrt(x**2))

power and squar root
 tensor([[0.1804, 0.7949, 0.1835, 0.6104, 0.4437],
        [0.5266, 0.8692, 0.3603, 0.5641, 0.3395],
        [0.7823, 0.9499, 0.6799, 0.1660, 0.8330],
        [0.4939, 0.4465, 0.1734, 0.0952, 0.6535]])


tensors are objects and have functions

In [57]:
print("\nY -\n Min:%.2f\n Max:%.2f\n Standard Deviation:%.2f\n Sum:%.2f" %(x.min(), x.max(), x.std(), x.sum()))


Y -
 Min:0.10
 Max:0.95
 Standard Deviation:0.26
 Sum:10.15


**tensor operations**

2 random 3d tensors

In [58]:
t1 = torch.rand(3,3,3)
t2 = torch.rand(3,3,3)

adding tensors

In [ ]:
print('addition\n', t1+t2)

addition
 tensor([[[1.0744, 0.4195, 1.3078],
         [1.5593, 0.9498, 1.2020],
         [0.8615, 1.2706, 1.0062]],

        [[0.5001, 0.7288, 0.6859],
         [0.9863, 1.0674, 1.6738],
         [1.3331, 0.4004, 1.0373]],

        [[1.0713, 1.3890, 0.4545],
         [1.2410, 1.0450, 1.7190],
         [0.9386, 1.8956, 0.9551]]])


**matrix multiplication cannot be done on 3D tensors**

you will need to treat the tensors as a batch (like a stack) of 2D tensors
this will let you preform matrix multiplication

In [ ]:
print("batch multiplation\n", torch.bmm(t1, t2))